/* Exact MIN over offsets of |A cap U_i A_i(c_i)| / |A| for the heavy {2,3} family, where
   A = image in (Z/M)^2 of a lattice L_A (subgroup generated by g1, g2 mod M); uniform measure on the coset
   A pushes forward to uniform measure on this image.  (Offset 0 WLOG: heavy offsets are free.)
   Heavy set i: { a_i k + b_i l == c_i mod e_i }.  Branch and bound: partial union only grows.
   stdin: M g1x g1y g2x g2y nH [a b e]*nH     stdout: minU_numer cellsA            */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
static int nH, W; static long cells; static uint64_t **bits; static int E[16];
static long best; static uint64_t *acc[17];
static void dfs(int d){
  long cnt=0; for(int w=0;w<W;w++) cnt+=__builtin_popcountll(acc[d][w]);
  if(cnt>=best) return;
  if(d==nH){ best=cnt; return; }
  /* try offsets in order of increasing new coverage (cheap heuristic: natural order) */
  for(int c=0;c<E[d];c++){
    uint64_t *b=bits[d]+(long)c*W;
    for(int w=0;w<W;w++) acc[d+1][w]=acc[d][w]|b[w];
    dfs(d+1);
    if(best==cnt) return;            /* cannot do better than current partial */
  }
}
int main(void){
  long M,g1x,g1y,g2x,g2y; if(scanf("%ld %ld %ld %ld %ld",&M,&g1x,&g1y,&g2x,&g2y)!=5) return 1;
  if(scanf("%d",&nH)!=1) return 1; long aH[16],bH[16];
  for(int i=0;i<nH;i++){ long e; if(scanf("%ld %ld %ld",&aH[i],&bH[i],&e)!=3) return 1; E[i]=(int)e; }
  /* enumerate cells of A */
  long cap=M*M; long *ck=malloc(sizeof(long)*cap), *cl=malloc(sizeof(long)*cap); cells=0;
  char *seen=calloc(cap,1);
  for(long x=0;x<M;x++) for(long y=0;y<M;y++){
    long k=((x*g1x+y*g2x)%M+M)%M, l=((x*g1y+y*g2y)%M+M)%M;
    if(!seen[k*M+l]){seen[k*M+l]=1; ck[cells]=k; cl[cells]=l; cells++;} }
  W=(int)((cells+63)/64); bits=malloc(sizeof(uint64_t*)*nH);
  for(int i=0;i<nH;i++){ bits[i]=calloc((size_t)E[i]*W,8);
    for(long x=0;x<cells;x++){ long c=(aH[i]*ck[x]+bH[i]*cl[x])%E[i]; bits[i][c*W+x/64]|=1ULL<<(x%64);} }
  for(int d=0;d<=nH;d++) acc[d]=calloc(W,8);
  best=cells+1; dfs(0);
  printf("%ld %ld\n",best,cells); return 0;
}
