// Independent exact coupled ratio  R = max_c (1-covA)/(1-covG-lam), lam = LN/LD, integer arithmetic.
// A = subgroup of (Z/144)^2 generated by g1=(a,c), g2=(0,d).  Heavy forms read from heavy.txt.
// Symmetry: translating by t in A preserves A and covG and maps c_i -> c_i - psi_i(t); we fix c_0 in
// a transversal of psi_0(A) in Z/e_0 (residues 0..g-1, g = gcd(e_0, psi_0(A))).
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#define M 144
#define NC (M*M)
typedef __int128 i128;
int n=9,E[9],Al[9],Be[9]; long nA; int WA,WG; uint64_t *bA[9],*bG[9],*accA[10],*accG[10];
long remG[10]; const long LN=485,LD=10000; long bnum=-1,bden=1,bca,bcg; int g0;
long pc(uint64_t*v,int W){long c=0;for(int w=0;w<W;w++)c+=__builtin_popcountll(v[w]);return c;}
// ratio = (nA-ca)*NC*LD / (nA*((NC-cg)*LD - LN*NC))
int better(long num,long den){ return (i128)num*bden > (i128)bnum*den; }
void dfs(int d){ long ca=pc(accA[d],WA), cg=pc(accG[d],WG);
  long num=(nA-ca)*(long)NC*LD, den=nA*((NC-cg-remG[d])*LD-LN*NC);
  if(den>0 && bnum>=0 && !better(num,den)) return;
  if(d==n){ den=nA*((NC-cg)*LD-LN*NC); if(bnum<0||better(num,den)){bnum=num;bden=den;bca=ca;bcg=cg;} return;}
  int cm= d==0? g0 : E[d];
  for(int o=0;o<cm;o++){ for(int w=0;w<WA;w++)accA[d+1][w]=accA[d][w]|bA[d][(long)o*WA+w];
    for(int w=0;w<WG;w++)accG[d+1][w]=accG[d][w]|bG[d][(long)o*WG+w]; dfs(d+1);} }
int main(int argc,char**argv){ long a=atol(argv[1]),c=atol(argv[2]),dd=atol(argv[3]);
  FILE*f=fopen("heavy_forms.txt","r"); for(int i=0;i<9;i++){int p; if(fscanf(f,"%d %d %d %d",&p,&E[i],&Al[i],&Be[i])!=4)return 1;}
  char*in=calloc(NC,1); long *idx=malloc(sizeof(long)*NC); nA=0;
  for(long x=0;x<M;x++)for(long y=0;y<M;y++){ long k=(x*a)%M, l=(x*c+y*dd)%M; in[k*M+l]=1; }
  for(long z=0;z<NC;z++) if(in[z]) idx[z]=nA++;
  WA=(nA+63)/64; WG=(NC+63)/64;
  for(int i=0;i<n;i++){ bA[i]=calloc((size_t)E[i]*WA,8); bG[i]=calloc((size_t)E[i]*WG,8);
    for(long k=0;k<M;k++)for(long l=0;l<M;l++){ long z=k*M+l; int v=(Al[i]*k+Be[i]*l)%E[i];
      bG[i][v*WG+z/64]|=1ULL<<(z%64); if(in[z]){long y=idx[z]; bA[i][v*WA+y/64]|=1ULL<<(y%64);} } }
  for(int d=0;d<=n;d++){accA[d]=calloc(WA,8);accG[d]=calloc(WG,8);}
  remG[n]=0; for(int d=n-1;d>=0;d--) remG[d]=remG[d+1]+NC/E[d];
  long g=E[0]; for(long z=0;z<NC;z++) if(in[z]){ long v=(Al[0]*(z/M)+Be[0]*(z%M))%E[0]; long p=g,q=v; while(q){long t=p%q;p=q;q=t;} g=p; } g0=g;
  dfs(0); printf("%ld %ld %ld %ld %d\n", bca, nA, bcg, (long)NC, g0); }
